# Azure Pipelines CI setup for cross-platform builds of Tad desktop app
#
# Set up triggers in GUI
name: $(Build.Reason)_$(Build.SourceBranch)_$(Rev:r)

# If we want to trigger on commits to master:
# trigger:
# - master

jobs:
  - job: Linux
    timeoutInMinutes: 15
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        displayName: "Use Node 16"
        inputs:
          versionSpec: 16.x
      - script: cat /etc/os-release
        displayName: "Get os release info"

  - job: macOS_12
    timeoutInMinutes: 15
    pool:
      vmImage: macOS-12
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: "Use node.js 16"
      - task: DownloadSecureFile@1
        name: devCertificate
        displayName: "Download Apple Dev Certificate"
        inputs:
          secureFile: "apple-dev-certificate.p12"
      - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@3
        displayName: "Install openssl from homebrew"
      - script: npm install
        displayName: "Install top-level npm dependencies"
      - script: npm run bootstrap
        displayName: "Run lerna bootstrapping"
      - script: "./tools/build-all.sh"
        displayName: "Build all packages"
      - script: "( cd packages/tad-app && npm run dist )"
        displayName: "Build packaged tad-app with electron-builder"
        env:
          {
            APPLEID: $(APPLEID),
            APPLEIDPASS: $(APPLEIDPASS),
            CSC_LINK: $(devCertificate.secureFilePath),
            CSC_KEY_PASSWORD: $(APPLEIDPASS),
          }
      - task: CopyFiles@2
        inputs:
          contents: "packages/tad-app/dist/Tad*.zip"
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          contents: "packages/tad-app/dist/Tad*.dmg"
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: MacOS12BuildOutputs
